services:
  - type: web
    name: django-app
    env: python
    region: oregon
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn -c gunicorn_config.py my_pro.wsgi:application"
    envVars:
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.11.0
